version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - /srv/elk/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - /srv/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  # logstash:
  #   build:
  #     context: logstash/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   container_name: logstash
  #   volumes:
  #     - /srv/elk/logstash/config:/usr/share/logstash/config:rw
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - /srv/elk/kibana/config:/usr/share/kibana/config:rw
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    volumes:
       - /srv/elk/filebeat/config:/usr/share/filebeat/config:rw
    ports:
       # Cisco ASA
       - "9001:9001/udp"
       # Cisco router
       - "514:9002/udp"
    environment:
       - ELASTICSEARCH_USERNAME=elastic
       - ELASTICSEARCH_PASSWORD=changeme
       - ELASTICSEARCH_HOST=elasticsearch
       - KIBANA_HOST=kibana
    # disable strict permission checks
    command: ["--strict.perms=false"]
    networks:
       - elk
    depends_on:
       - elasticsearch
       - kibana

networks:
  elk:
    driver: bridge
